### ISSUE TITLE
signalR server onConnected not firing

### ISSUE THREAD

**Issue by Johnathon332** [TargetProcess/signalr-client-py#10]
When I call connection.start on my python signalr client, The server overrides the OnConnected function which should fire when the python client connection initiates. 

public override Task OnConnected()
        {
            Console.Write("");
            return base.OnConnected();
        }

**Comment by u-abramchuk** [comment]
Hi Johnathon332,

thank you for the report. The fix will be available in the next version.

**Comment by u-abramchuk** [comment]
Fixed in version 0.0.7
