### ISSUE TITLE
Polling - connection.wait()

### ISSUE THREAD

**Issue by ThePaceMaker** [TargetProcess/signalr-client-py#16]
Hi

When sending polling data up to the server, you are forced to call the wait function with a given timeout to receive the response from the server. Should the timeout not be of a suitable time period (server processing takes longer, than the wait timeout), the response never makes it back to the client. 

I have tried two different ways to handle this: 

Client:

`def print_received_message(data):
            print('received message: ', data)

chat.client.on('newMessageReceived', print_received_message)

infinite = 1
while infinite == 1:
    with connection:
      print('Sending information...')
        data = 'some processed data'
        chat.server.invoke('send', data) # server takes time to process this
        connection.wait(heartbeat)`

Server:

     public Task Send(string data)
        {
            string response = $"{data} - Saved To Server {DateTime.Now}";
            Thread.Sleep(5000) // mimic server processing
            return Clients.All.newMessageReceived(response);
        }

This is because the connection gets closed and the reopened again. I know that wait closes the connection (by design), but this is the only way I could the information sent back to the client, with a large timeout period. Not very efficient due to the timeout and the continuous opening and closing of sockets

If you remove the connection.wait() and replace it with a time.sleep() the following error is raised

   raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
<Greenlet at 0x3e18bc0: wrapped_listener> failed with WebSocketConnectionClosedException

if I change the code to following and move the the connection and wait outside of the loop, The newMessageReceived method is never raised on the client, but the data does make it to the server and processed accordingly

Client:

def print_received_message(data):
            print('received message: ', data)

infinite = 1
with connection:
     while infinite == 1:
           print('Sending information...')
           data = 'some processed data'
           chat.server.invoke('send', data) # server takes time to process this
connection.wait(1)

Server:

     public Task Send(string data)
        {
            string response = $"{data} - Saved To Server {DateTime.Now}";
            Thread.Sleep(5000) // mimic server processing
            return Clients.All.newMessageReceived(response);
        }
Hope this makes sense to you all.

**Comment by WojciechMigda** [comment]
I am experiencing `WebSocketConnectionClosedException` exception being thrown in my client's code. I tried catching it (in the most wide scope: around `with Session() as session:` block), but it appears that this is not a place to handle it. Can someone recommend where to catch `WebSocketConnectionClosedException` so that I could re-connect my client?

**Comment by ngunhaSO** [comment]
@WojciechMigda: I am facing the same issue. When the signalr server was down, my django just throws a bunch of exception in the middle of nowhere. I am not sure where to catch these exceptions...

**Comment by k12007** [comment]
facing the same issue :(
