### ISSUE TITLE
Document setup needed to verify SignalR server's custom certificate using HTTPS

### ISSUE THREAD

**Issue by gokhansengun** [TargetProcess/signalr-client-py#31]
SignalR server is running HTTPS with a certificate signed with a custom certificate chain.

Using `signalr-client` can not verify the certificate and produce the below error. The fact that `websocket` package needs to be informed about custom CA file needs documenting.

Error:

```
  File "/usr/local/lib/python3.4/dist-packages/gevent/_ssl3.py", line 232, in __init__
    raise x
  File "/usr/local/lib/python3.4/dist-packages/gevent/_ssl3.py", line 228, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.4/dist-packages/gevent/_ssl3.py", line 545, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

**Comment by coin8086** [comment]
I think you can put `session.verify = False`, in which the `sesssion` is used for a singalr connection, to skip SSL verification.

**Comment by gokhansengun** [comment]
@coin8086 `session.verify = False` disables SSL/TLS verification altogether, making the use of SSL/TLS meaningless and very dangerous.

**Comment by gokhansengun** [comment]
What worked for me to set `CERTIFICATE_CHAIN_PATH` to the custom certificate chain path.
