### ISSUE TITLE
Error when using WSS

### ISSUE THREAD

**Issue by nimble99** [TargetProcess/signalr-client-py#9]
When using WebSocket transport, and HTTPS, the following error is caused on connection:

>   File "/home/pi/signalr/_connection.py", line 49, in start
>     listener = self.__transport.start()
>   File "/home/pi/signalr/transports/_auto_transport.py", line 30, in start
>     return self.__transport.start()
>   File "/home/pi/signalr/transports/_ws_transport.py", line 36, in start
>     enable_multithread=True)
>   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 105, in create_connection
>     websock.connect(url, **options)
>   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 269, in connect
>     options.pop('socket', None))
>   File "/usr/local/lib/python2.7/dist-packages/websocket/_http.py", line 73, in connect
>     sock = _ssl_socket(sock, options.sslopt, hostname)
>   File "/usr/local/lib/python2.7/dist-packages/websocket/_http.py", line 170, in _ssl_socket
>     sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
>   File "/usr/local/lib/python2.7/dist-packages/websocket/_http.py", line 155, in _wrap_sni_socket
>     server_hostname=hostname,
>   File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
>     _context=self)
>   File "/usr/lib/python2.7/ssl.py", line 565, in __init__
>     raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
> ValueError: do_handshake_on_connect should not be specified for non-blocking sockets

**Comment by nimble99** [comment]
Hmmm. I have actually fixed this by removing the socket monkey patching....

**Comment by u-abramchuk** [comment]
Hi, thank you for reporting. I'll look into it.

**Comment by u-abramchuk** [comment]
Fixed in version 0.0.7
